modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
issueTrackerURL="https://github.com/Mrthomas20121/TFC_tinkers/issues"

[[mods]]
modId="tfc_tinkers"
version="0.0.1"
displayName="TFC Tinkers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tfc_tinkers"
authors="Mrthomas20121"
description='''
Add new decorative blocks to TFC.
'''

[[dependencies.tfc_tinkers]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    side="BOTH"